Debug anchore grype pipeline
RAJANAGORI/Nightingale pull request #76
Opened 2024-10-05 11:19 UTC by Sidbhasin13

2024-11-09 07:05 UTC, RAJANAGORI commented on Dockerfile
@Sidbhasin13 this change should be done in the programming dockefile as that image is considered as the base image of the Nightingale's final docker image. 
For for information, Please refer to the architecture diagram in the wiki link. Let me know your doubts.

2024-11-09 07:08 UTC, RAJANAGORI requested changes
@Sidbhasin13 Thanks for the changes but there is a request to add the config of the Dockerfile in the programming image file under the Dockerfiles folder.

2024-11-11 17:15 UTC, Sidbhasin13 commented on Dockerfile
@RAJANAGORI made the changes as per your suggestions.

2024-11-12 16:37 UTC, RAJANAGORI approved these changes

2024-11-12 16:37 UTC, merged

2024-11-12 16:38 UTC, RAJANAGORI commented
Changes Merged !!